language: rust
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
    # Update GTK3 in Docker image
    - WD="$PWD"
    - cd "$HOME"
    - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/gtk-3.18.1-2/deps.txz"
    - tar xf deps.txz
    - cd "$WD"
    - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
    # Build the application
    - cargo build --verbose --features "enable_gtk"
